"""empty message

Revision ID: 2bfbd1ce0ac1
Revises: c8876fe12bef
Create Date: 2025-01-04 13:17:16.088548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2bfbd1ce0ac1'
down_revision = 'c8876fe12bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###
