"""empty message

Revision ID: 74e25694aaee
Revises: 2bfbd1ce0ac1
Create Date: 2025-01-04 13:18:54.716543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '74e25694aaee'
down_revision = '2bfbd1ce0ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('important', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('important')

    # ### end Alembic commands ###
